config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :order_products
  resources :orders
  resources :cart_products
  resources :products do
    member do
      post 'add_to_cart'
    end
  end
  resources :carts
  resources :users do
    member do
      patch :update_admin_status
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_one :cart
  validates :email, presence: true, uniqueness: true
  after_create :create_cart

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  def last_admin?
    User.where(isadmin: true).count == 1 && self.isadmin?
  end
  def create_cart
    Cart.create(user: self)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy update_admin_status]
  before_action :authenticate_user!
  before_action :correct_user_or_admin, only: %i[show edit update destroy update_admin_status]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @orders = @user.orders
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: '' }
        format.json { render :show, status: :created, location: @user }
        flash[:success] = "L'utilisateur a été créé avec succès !"
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Le profil a été modifié avec succès.'
    else
      render :edit
    end
  end

  # PATCH /users/1/update_admin_status
  def update_admin_status
    if @user.last_admin? && params[:user][:isadmin] == "0"
      redirect_to @user, alert: 'Cannot remove admin status from the last admin.'
    elsif @user.update(admin_status_params)
      redirect_to @user, notice: 'Admin status was successfully updated.'
    else
      redirect_to @user, alert: 'Failed to update admin status.'
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    if current_user.isadmin? || @user == current_user
      if @user.last_admin?
        redirect_to users_url, alert: 'Cannot delete the last admin.'
      else
        @user.destroy!
        respond_to do |format|
          format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
    else
      redirect_to root_path, alert: 'Access denied.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone_number, :billing_address, :delivery_address, :isadmin)
  end

  def admin_status_params
    params.require(:user).permit(:isadmin)
  end

  def correct_user_or_admin
    unless @user == current_user || current_user.isadmin?
      redirect_to root_path, alert: 'Access denied.'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin_profile.html.erb
<h2>Admin Options</h2>
<p>Role: Admin</p>
<%= link_to 'Manage Users', users_path %>
<%= link_to 'Admin Dashboard', admin_dashboard_path %>
<!-- Any other admin-specific options or information -->

app/views/users/_form.html.erb
<div class="max-w-lg bg-white border border-gray-200 rounded-lg shadow flex flex-col m-6 p-5">
  <h2 class="text-2xl font-bold tracking-tight text-gray-900 mb-4 flex justify-center">Edit User</h2>

  <%= form_with(model: user, local: true, html: { class: 'space-y-4' }) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation" class="mb-4">
        <h2 class="text-lg font-semibold text-red-600"><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul class="list-disc list-inside text-red-600">
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :first_name, 'Prénom', class: 'block mb-2 text-sm font-medium text-gray-900' %>
      <%= form.text_field :first_name, class: 'w-full p-2.5 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500' %>
    </div>

    <div class="field">
      <%= form.label :last_name, 'Nom', class: 'block mb-2 text-sm font-medium text-gray-900' %>
      <%= form.text_field :last_name, class: 'w-full p-2.5 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500' %>
    </div>

    <div class="field">
      <%= form.label :email, class: 'block mb-2 text-sm font-medium text-gray-900' %>
      <%= form.email_field :email, class: 'w-full p-2.5 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500' %>
    </div>

    <div class="field">
      <%= form.label :password, class: 'block mb-2 text-sm font-medium text-gray-900' %>
      <%= form.password_field :password, autocomplete: "new-password", class: 'w-full p-2.5 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500' %>
    </div>

    <div class="field">
      <%= form.label :password_confirmation, class: 'block mb-2 text-sm font-medium text-gray-900' %>
      <%= form.password_field :password_confirmation, autocomplete: "new-password", class: 'w-full p-2.5 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500' %>
    </div>

    <div class="actions flex justify-center">
      <%= form.submit "Update", class: 'w-1/2 px-4 py-2 text-white btn-success' %>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/_user_profile.html.erb
<h2>User Information</h2>
<p>Role: User</p>
<!-- Add other user-specific information or options here -->

app/views/users/edit.html.erb
<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1 class="text-2xl font-bold text-center mt-4 py-4">Users</h1>

<div class="max-w-4xl mx-auto bg-white shadow-md rounded-lg overflow-hidden my-6">
  <table class="min-w-full bg-white">
    <thead>
      <tr>
        <th class="py-2 px-4 border-b-2 border-gray-200 bg-red-100 text-center leading-4 font-medium text-gray-800 uppercase tracking-wider text-lg">Name</th>
        <th class="py-2 px-4 border-b-2 border-gray-200 bg-red-100 text-center leading-4 font-medium text-gray-800 uppercase tracking-wider text-lg">Email</th>
        <th class="py-2 px-4 border-b-2 border-gray-200 bg-red-100 text-center leading-4 font-medium text-gray-800 uppercase tracking-wider text-lg">Actions</th>
      </tr>
    </thead>
    <tbody class="bg-white">
      <% @users.each do |user| %>
        <tr>
          <td class="py-4 px-6 border-b border-gray-200"><%= user.first_name %> <%= user.last_name %></td>
          <td class="py-4 px-6 border-b border-gray-200"><%= user.email %></td>
          <td class="py-4 px-6 border-b border-gray-200">
            <%= link_to 'Show', user_path(user), class: 'btn btn-primary mr-2' %>
            <% if current_user.isadmin? %>
              <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-secondary mr-2' %>
              <%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<div class="flex flex-col justify-center items-center">
  <h1 class="my-4 text-3xl">Welcome back <%= @user.first_name %>!</h1>

  <div class="profile-container my-6">
    <p class="my-1"><strong>First Name:</strong> <%= @user.first_name %></p>
    <p class="my-1"><strong>Last Name:</strong> <%= @user.last_name %></p>
    <p class="my-1"><strong>Email:</strong> <%= @user.email %></p>
    <p class="my-1"><strong>Joined:</strong> <%= @user.created_at.strftime("%B %d, %Y") %></p>
  </div>

  <% if @user.isadmin? %>
      <h2 class="text-3xl mt-3">Admin Options</h2>
    <div class="bg-white border border-gray-200 rounded-lg shadow flex flex-col justify-center items-center mt-2 mb-6 p-2">
      <div class="p-6">
        <%= link_to 'Manage Users', users_path, class: 'btn btn-secondary mx-2' %>
        <%= link_to 'Admin Dashboard', "admin_dashboard_path", class: 'btn btn-primary mx-2' %>
        <div class="flex flex-row justify-center items-center mt-4">
          <%= form_with(model: @user, url: update_admin_status_user_path(@user), method: :patch, local: true) do |form| %>
            <div class="form-group mx-5 my-2">
              <%= form.label :isadmin, 'Admin Status' %>
              <%= form.check_box :isadmin %>
            </div>
            <%= form.submit 'Update Admin Status', class: 'btn btn-success' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>



  <div class="flex flex-col justify-center items-center mx-6 p-6">
    <h2 class="text-3xl mt-3">Previous Orders</h2>
    <div class="overflow-x-auto ">
      <% if @orders.present? %>
        <table class="min-w-full bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 mt-2 mb-3 p-6">
          <thead>
            <tr>
              <th class="px-4 py-2 border-b border-gray-200 dark:border-gray-700">Order ID</th>
              <th class="px-4 py-2 border-b border-gray-200 dark:border-gray-700">Date</th>
              <th class="px-4 py-2 border-b border-gray-200 dark:border-gray-700">Total</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td class="px-4 py-2 border-b border-gray-200 dark:border-gray-700"><%= order.id %></td>
                <td class="px-4 py-2 border-b border-gray-200 dark:border-gray-700"><%= order.created_at.strftime("%B %d, %Y") %></td>
                <td class="px-4 py-2 border-b border-gray-200 dark:border-gray-700">$<%= order.total_price %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p class="p-4 text-center">No previous orders.</p>
      <% end %>
    </div>
  </div>


    <div class="flex flex-col justify-center items-center mt-2 mb-6 p-6">
    <h2 class="text-3xl mt-3">User Options</h2>

    <div class="flex flex-row justify-around items-center m-2 p-2">
      <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-secondary mx-8" %>

      <%= link_to 'Delete account', user_path(@user), method: :delete, data: { confirm: 'Are you sure you want to delete this user?' }, class: 'btn btn-danger mx-8' %>
    </div>
  </div>
</div>