config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :order_products
  resources :orders
  resources :cart_products
  resources :products do
    member do
      post 'add_to_cart'
    end
  end
  resources :carts
  resources :users do
    member do
      patch :update_admin_status
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"
end

app/views/shared/_banner.html.erb
<div class="w-11/12 grid grid-cols-2 gap-8 items-center bg-cover bg-center relative rounded-t-lg mt-8" style="background-image: url('<%= asset_path("header background.webp") %>'); height: 400px;">
  <div class="col-span-1">
    <div class="flex flex-col p-8">
        <div class="z-10 p-6 text-start">
        <h1 class="text-4xl font-bold text-white mb-4">Le meilleur de la charcuterie Sicilienne</h1>
        <div class="mt-10">
            <%= link_to 'Andiamo!', 'https://www.youtube.com/watch?v=hg9gvz5n614', class: 'btn btn-secondary' %>
        </div>
        </div>
    </div>
  </div>
  <div class="col-span-1"></div>
</div>

app/views/shared/_card.html.erb
<div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
  <%= link_to '#' do %>
    <%= image_tag 'products/guanciale_01.png', class: 'rounded-t-lg', alt: '' %>
  <% end %>
  <div class="p-5">
    <%= link_to '#' do %>
      <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
    <% end %>
    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
    <%= link_to '#', class: 'inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' do %>
      Read more
      <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
      </svg>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-neutral-700 shadow dark:bg-neutral-700">
    <div class="w-full max-w-screen-xl mx-auto p-4 md:py-8">
        <div class="sm:flex sm:items-center sm:justify-between">
          <%= link_to products_path, class: 'flex  space-x-3 rtl:space-x-reverse text-white' do %>
          <div class="w-16 h-16 fill-current text-white">
            <%= image_tag 'logos/logo_small.svg', alt: 'Logo' %>
          </div>
          <span class="self-center text-2xl font-sans whitespace-nowrap text-white hidden md:block">Coppa & Gabana</span>
        <% end %>

        <ul class="flex flex-wrap my-2 mb-6 text-sm font-medium text-white sm:mb-0">
        <li>
            <%= mail_to 'hello@coppaandgabana', class: 'hover:underline' do %>
            Contact
            <% end %>
        </li>
        </ul>

        </div>
        <hr class="my-6 border-gray-200 sm:mx-auto dark:border-neutral-700 lg:my-8" />
        <span class="block text-sm text-white sm:text-center">© 2023 <a href="#" class="hover:underline">Coppa & Gabana™</a>. All Rights Reserved.</span>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="bg-pink-900 text-white">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <%= link_to root_path, class: 'flex items-center space-x-3 rtl:space-x-reverse text-white' do %>
      <div class="w-16 h-16 fill-current text-white">
        <%= image_tag 'logos/logo_small.svg', alt: 'Logo' %>
      </div>
      <span class="self-center text-2xl font-sans whitespace-nowrap hidden md:block">Coppa & Gabana</span>
    <% end %>
    
    <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
      <% if user_signed_in? %>
        <%= link_to user_path(current_user), class: "btn-primary mr-4 hover:text-amber-400 hover:bg-pink-900" do %>
          <i class="fa-solid fa-user"></i> Profile
        <% end %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn-secondary" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "btn-primary mx-4 pr-4" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn-secondary mx-4" %>
      <% end %>
      <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-white rounded-lg md:hidden hover:bg-amber-500 focus:outline-none focus:ring-2 focus:bg-amber-500" aria-controls="navbar-sticky" aria-expanded="false" id="burger-menu">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
      </button>
    </div>
    <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
      <ul class="flex flex-col p-4 md:p-0 mt-4 md:space-x-14 rtl:space-x-reverse md:flex-row md:mt-0 font-sans">
        <li>
          <%= link_to root_path, class: 'block py-2 px-3 text-white font-bold hover:text-amber-400', aria_current: 'page' do %>
            <i class="fa-solid fa-home"></i>
            Home
          <% end %>
        </li>
        <% if user_signed_in?%>
          <li>
            <%= link_to cart_path(current_user), class: 'block py-2 px-3 text-white font-bold hover:text-amber-400', aria_current: 'page' do %>
              <i class="fa-solid fa-cart-shopping"></i>
              Cart
            <% end %>
          </li>
        <% end %>
        <li>
        </li>
      </ul>
    </div>
  </div>
</nav>