config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :order_products
  resources :orders
  resources :cart_products
  resources :products do
    member do
      post 'add_to_cart'
    end
  end
  resources :carts
  resources :users do
    member do
      patch :update_admin_status
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  # Validate that each user has at most one cart
  validates :user_id, uniqueness: true
  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /cart
  def cart
    @cart_products = current_user.cart_products # Logic to retrieve cart items for the current user
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/1/edit
  def edit
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

 
   def destroy
   end

  private
    # Use this callback to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_product_params
      params.require(:cart_product).permit(:cart_id, :product_id, :quantity)
    end
    
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<div id="<%= dom_id @cart %>" class="max-w-3xl mx-auto bg-white rounded-lg shadow-md flex flex-col justify-center my-6 p-8">
  <h2 class="text-2xl font-bold text-gray-800 mb-4 mt-2 text-center">Cart</h2>
  <% @cart.cart_products.each do |cart_product| %>
    <div id="<%= dom_id cart_product %>" class="mb-4 p-4 border-b border-gray-200">
      <p class="flex justify-between items-center text-lg text-gray-700">
        <span>
          <strong>Product: </strong> <%= cart_product.product.title %>
        </span>
        <span class="text-amber-500 pl-8"><%= number_to_currency(cart_product.product.price) %></span>
      </p>
    </div>
  <% end %>
  <p class="text-xl font-semibold text-gray-800 mt-6 flex justify-between items-center">
    <span>Total Price: </span>
    <span class="text-amber-500"><%= number_to_currency(@cart.cart_products.sum { |cart_product| cart_product.product.price }) %></span>
  </p>

  <div class="mt-6 flex justify-center">
    <%= link_to "Checkout", products_path, class: "btn btn-success text-center" %>
  </div>
</div>



<!--<div>
  <%= link_to "Edit this cart", edit_cart_path(@cart) %> |
  <%= button_to "Destroy this cart", @cart, method: :delete %>
</div>-->