config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :order_products
  resources :orders
  resources :cart_products
  resources :products do
    member do
      post 'add_to_cart'
    end
  end
  resources :carts
  resources :users do
    member do
      patch :update_admin_status
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_product, dependent: :destroy
  has_many :orders, through: :order_product, dependent: :destroy
  has_many :cart_product, dependent: :destroy
  has_many :carts, through: :cart_product, dependent: :destroy
  has_one_attached :photo
  validates :title, presence: true
  validates :category, presence: true
  validates :subtitle, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_admin, only: [:edit, :update, :destroy]
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    if params[:category_ids].present?
      @products = Product.where(category: params[:category_ids])
    else
      @products = Product.all
    end
  end

  # GET /products/1 or /products/1.json
  def show

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product) }
        format.json { render :show, status: :created, location: @product }
        flash[:success] = "Le produit a été créé avec succès !"
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        flash[:error] = "Il y a eu un problème lors de la création du produit."
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "" }
        format.json { render :show, status: :ok, location: @product }
        flash[:success] = "Le produit a été modifié avec succès !"
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Le produit a été supprimé avec succès." }
      format.json { head :no_content }
    end
  end

  private
    def require_admin
      redirect_to root_path, alert: "You are not authorized to perform this action." unless current_user.isadmin?
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :category, :subtitle, :description, :price, :photo)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_checkboxes.html.erb
<%= form_tag(products_path, method: :get, id: 'filter-form') do %>
  <div class="flex flex-row justify-center py-4">
    <% Product.distinct.pluck(:category).each do |category| %>
      <div class="flex items-center ps-4 border border-gray-200 rounded px-4 mx-4">
        <%= check_box_tag "category_ids[]", category, params[:category_ids]&.include?(category), id: "#{category.parameterize}_checkbox", class: "w-4 h-4 text-amber-500 bg-gray-100 border-gray-300 rounded focus:ring-amber-500 dark:focus:ring-amber-500 focus:ring-2" %>
        <label for="<%= "#{category.parameterize}_checkbox" %>" class="w-full py-4 ms-2 text-sm font-medium text-gray-900"><%= category %></label>
      </div>
    <% end %>
  </div>
  
  <%# submit_tag "Filter", class: "bg-amber-500 hover:bg-amber-600 text-white font-bold py-2 px-4 rounded" %>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4">
      <h2 class="font-bold"><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul class="mt-2">
        <% product.errors.full_messages.each do |message| %>
          <li class="list-disc list-inside"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class= "w-full bg-slate-50 rounded-lg shadow-lg m-6 p-8">

  <div class="text-3xl text-white font-bold my-8 bg-pink-950 rounded flex justify-center items-center h-32">
    <h1>Nouveau produit !</h1>
  </div>

  <div class="mb-4">
    <%= form.label :title, class: "block text-gray-700 text-lg font-bold mb-2 " %>
    <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700  hover:bg-slate-50" %>
  </div>

  <div class="mb-4">
    <%= form.label :category, class: "block text-gray-700 text-lg font-bold mb-2" %>
    <%= form.select :category, options_for_select(["Charcuterie", "Fromage"], selected: product.category), {}, class: "block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded   hover:bg-slate-50" %>
  </div>

  <div class="mb-4 text-wrap">
    <%= form.label :subtitle, class: "block text-gray-700 text-lg font-bold mb-2" %>
    <%= form.text_area :subtitle, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 h-12 hover:bg-slate-50 text-wrap" %>
  </div>

  <div class="mb-4">
    <%= form.label :description, class: "block text-gray-700 text-lg font-bold mb-2" %>
    <%= form.text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 h-32 hover:bg-slate-50 text-wrap" %>
  </div>

  <div class="mb-4">
    <%= form.label :price, class: "block text-gray-700 text-lg font-bold mb-2" %>
    <%= form.text_field :price, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 hover:bg-slate-50" %>
  </div>

  <div class="mb-4">
    <%= form.label :photo, class: "block text-gray-700  font-bold mb-2" %>
    <%= form.file_field :photo, class: "block w-full text-gray-700 py-2 px-3 border rounded hover:bg-slate-50" %>
  </div>

  <div class="actions flex justify-center items-center mt-10">
    <%= form.submit class: "btn btn-success mt-10" %>
  </div>

    <div class="flex flex-col items-center space-y-2 mt-10">
    <%= link_to products_path, class: "btn btn-primary-icon" do %>
      <i class="fa-solid fa-arrow-left"></i>
    <% end %>
    <h4>Back to products</h4>
  </div>
</div>

<% end %>
`

app/views/products/_product.html.erb
<div id="<%= dom_id product %>" class="w-96 bg-white border border-gray-200 rounded-lg shadow flex flex-col m-6">
  <%= link_to product do %>
      <% if product.photo.attached? %>
        <%= image_tag product.photo, class: "w-full h-48 object-cover rounded-t-lg" %>
      <% else %>
        <img src="placeholder_image_url" alt="Placeholder" class="w-full h-48 object-cover">
      <% end %>
  <% end %>
  <div class="flex-grow mx-4 p-1">
    <div class="flex flex-row justify-between">
      <%= link_to product do %>
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 hover:text-gray-800"><%= product.title %></h5>
      <% end %>
      <p class="my-1 text-gray-800 italic"><%= product.category%></p>
    </div>

    <p class="mb-3 font-normal text-gray-700"><%= product.subtitle %></p>

    <p class="text-gray-900 font-semibold mb-2"><%= product.price %>€</p>
  </div>

  <div class="m-4">
    <div class="flex justify-between">
      <% if user_signed_in? && current_user.isadmin? %>
        <%= link_to edit_product_path(product), class: "btn btn-secondary mx-2" do %>
          Edit
        <% end %>
        <%= button_to product, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" do %>
          Delete
        <% end %>
      <% end %>
      <%= link_to product, class: "btn btn-primary-icon" do %>
        <i class="fa-solid fa-arrow-right"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<div class="flex flex-col justify-center items-center">

  <%= render partial: "shared/banner" %>

  <h1 class=" my-4 text-5xl">Nos produits</h1>

  <%= render partial: "checkboxes"%>

  

  <% if user_signed_in? && current_user.isadmin? %>
  <%= link_to "New product", new_product_path, class: "btn btn-success my-4" %>
  <% end %>

  <div id="products" class="flex flex-row justify-center flex-wrap content-evenly min-w-64">
    <% @products.each do |product| %>
      <%= render product %>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<!-- app/views/products/new.html.erb -->

<div class= "w-screen px-96 mb-12">
<%= render "form", product: @product %>
<br>

app/views/products/show.html.erb
<main class="max-w-6xl my-8 mb-32 p-8 pt-24 pb-10 gap-6 bg-white rounded-lg shadow-lg flex flex-col md:flex-row">
    <!-- Product Image -->
    <section class="mx-auto mt-14 h-96 md:w-1/2 flex justify-center md:justify-center">
        <%= image_tag @product.photo || "products/guanciale_01.png", class: "rounded-lg shadow-lg", alt: @product.title %>
    </section>
    <!-- Product Details -->
    <section class="w-full md:w-1/2 md:ml-6 mt-6 md:mt-0">
        <h2 class="text-4xl md:text-3xl text-slate-900 font-bold mb-4"><%= @product.title %></h2>
        <h2 class="text-2xl md:text-2xl text-slate-900 mb-4">500g</h2>
        <p class="text-lg md:text-xl text-gray-700 mb-4"><%= @product.description %></p>
        <h2 class="text-2xl md:text-3xl text-amber-800 mb-4"><%= @product.price %>€</h2>
        
        <div class="mb-8 p-1 ">
            <h2 class="block mb-4">Quantité:</h2>
            <div class="flex items-center gap-3">
                <%= link_to "#", class: "btn btn-primary-icon" do %>
                    <i class="fa-solid fa-minus"></i>
                <% end %>
                <span class="text-xl">1</span>
                <%= link_to "#", class: "btn btn-primary-icon" do %>
                    <i class="fa-solid fa-plus"></i>
                <% end %>
            </div>
        </div>

        <%= button_to "Add to Cart", add_to_cart_product_path(@product), method: :post, class: "btn btn-secondary text-base font-extralight" %>
    </section>
</main>